### ISSUE TITLE
Visual error

### ISSUE THREAD

**Issue by ferranalvarez** [TomLinthwaite/SKTilemap#5]
Hello Tom.

I'm just testing your library and works pretty well!

My problem maybe has nothing to do with your library. I have added a node which the camera keeps on the center all the time. This node moves at constant velocity and does well when its moving at a low speed. But when I increase it,  some vertical lines appear between the tiles. Do you know how to solve it? Thanks!

edit: btw It only happens when moving horizontally, and i'm using an iPad to test it (60 framerate)
![tiles2](https://cloud.githubusercontent.com/assets/2863434/14672598/2ac558d4-06f9-11e6-8a36-7018883f4443.gif)

**Comment by TomLinthwaite** [comment]
Hi thanks for the feedback. 

I've encountered this problem several times in other frameworks/engines to. I don't think there's any work I can do to improve it through the project, but there are ways you can.

The easiest to try is to make sure the scale of the camera or tilemap node is divisible by the tile size since weird floating points can cause this during rendering. I can't tell if your zoomed out there but hopefully that's the case.

The other way to try is by making your tiles have a 1 pixel border around the edge within the Sprite sheet (not just blank space but a continuation of colour) but keep the tile size the same. This might reduce the tear. 

I'm at work at the moment so can't test these but let me know if it helps. 

Other than that just try googling "tear in tilemaps" or something that might give some other answers I can't think of.

Hope this helps.

**Comment by TomLinthwaite** [comment]
I just watched your gif again and can see it's probably the camera itself being at a weird floating point number. See if you can keep the camera at a whole number or divisible of the tile size when repositioning it.

**Comment by ferranalvarez** [comment]
Thanks for your answer.

I've just used Integers instead of floats (the decimals where causing it) on the camera position and tearing has been solved. 
:)

**Comment by TomLinthwaite** [comment]
No problem glad I could help :)

**Comment by ravenshore** [comment]
It seems that you are already using Int in the Camera position updates, but I still see the lines when panning across. Ideas ?

**Comment by TomLinthwaite** [comment]
I assume you've tried everything in this post? Can you give me some sample code or some details? Does this happen in the example? I haven't seen the tearing since I made that update and I use this every day in my game. I'm eager to sort it out though

**Comment by ravenshore** [comment]
I haven't spent too much time on it yet. I was looking for the best solution for using tiled maps.
I loaded your project and it has the lines right off the bat on every sim and on a real device as well.
I created my own project and a map and I still have it.
I know it's because of the retina point / pixel ratio , but I looked at your camera code and you are already using Int for the X and Y for the updated camera position when moving, before you cast it to CGPoint, so not sure...

**Comment by ravenshore** [comment]
Thanks for the quick reply btw !

**Comment by TomLinthwaite** [comment]
This is weird because I cannot make those lines appear with the current build using the example. I tried on 5s and 6plus and all the simulators. Probably a stupid question but you have the latest build right? I can’t think of why it would act differently. About to get off for the night got work tomorrow I’ll mull it over then :P

**Comment by ravenshore** [comment]
I'Il re-download, but I got the build from GH a couple of days ago.
Also I was examining the code on my machine.
I'll test again tonight and let you know.

**Comment by TomLinthwaite** [comment]
I've been thinking about this and can't for the life of me think why this might be happening. Any chance you can post a gif of it? Might help me realise what the issue is. As I said I can't recreate the issue so I can't know if it's fixed :P 

Only thing I can suggest is you disable the camera and try to write some basic code that will move the map. Or maybe create your own map in tiled. Load it and test it with the camera and see if you get the same results. It's a shame I don't have a bigger user test base for this >.<

Let me know if you manage to find a solution

**Comment by ravenshore** [comment]
I'll try and do that tonight.
I already tried with my own map and it's absolutely the same.
Will do. Thanks.

**Comment by ravenshore** [comment]
Just re-downloaded and tested. 
Now the lines only appear if I zoom in and out now, not sure what changed.
So I think I can figure this out.
Thanks for the help !

**Comment by TomLinthwaite** [comment]
OK excellent. Let me know if you need help with anything in the future :)
